---
title: "script"
author: "Yao Yu"
date: "2022-11-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(googlesheets4)
library(janitor)
library(reactable)
library(scales)

data <- read_sheet("1J7d9G0d2w-D7vS61Bds4UI5TyBP5ERcBmR-u_UJG0jU") %>% 
  clean_names()
```

```{r avg_dem_2party, fig.height = 1, fig.width = 3}
boxplot_data <- data %>% 
  drop_na(avg_dem_2party) %>% 
  mutate(margin = avg_dem_2party - 50) %>% 
  mutate(win = ifelse(margin < 0, "R", "D"))

margin_median <- median(boxplot_data$margin)

boxplot <- boxplot_data %>% 
  ggplot() +
  geom_boxplot(aes(x = margin, y= ""), width=.2) +
  geom_jitter(aes(x = margin, y = "", color = win), width = 0, height = 0.05) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  annotate("text", x = margin_median - 0.2, y = 1.25, label = str_c("Median: R+", abs(margin_median)),
           size = 5) + 
  scale_color_manual(values=c("#619CFF", "#F8766D")) +
  scale_x_continuous(limits = c(-4, 2), breaks = c(-4, -3, -2, -1, 0, 1, 2),
                     labels = c("R+4", "R+3", "R+2", "R+1", "0", "D+1", "D+2")) +
  theme_minimal() +
  theme(legend.position="none",
        text = element_text(size = 14)) +
  labs(x = "", 
       y = "")

png("boxplot_2022.png", units = "in", width = 6, height = 3, res = 300)
print(boxplot)
dev.off()
```

```{r histogram}
hist_data <- data %>% 
  select(d_seats, r_seats) %>% 
  drop_na() %>% 
  mutate(win = ifelse(d_seats > r_seats, "D", "R")) %>% 
  pivot_longer(d_seats:r_seats) %>% 
  filter(name == "d_seats") %>% 
  mutate(margin = value - 218)

margin_median <- median(hist_data$margin)

hist_plot <- hist_data %>% 
  ggplot() +
  geom_density(aes(x = margin, fill = win, color = win), alpha = 0.25) +
  geom_jitter(aes(x = margin, y = 0.02, color = win), height = 0.01, width = 0) +
  # geom_col(aes(x = margin, y = 0.02, fill = win)) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = margin_median, linetype = "solid") +
  annotate("text", x = margin_median - 6, y = 0.05, label = str_c("Median: R+", abs(margin_median)),
           size = 5) + 
  scale_color_manual(values=c("#619CFF", "#F8766D")) +
  scale_fill_manual(values=c("#619CFF", "#F8766D")) +
  scale_x_continuous(limits = c(-30, 30), breaks = c(-30, -20, -10, 0, 10, 20, 30),
                     labels = c("R+30", "R+20", "R+10", "0", "D+10", "D+20", "D+30")) +
  theme_minimal() +
  theme(legend.position="none",
        text = element_text(size = 14),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()) +
  labs(x = "",
       y = "")

png("histogram_2022.png", units = "in", width = 7, height = 4, res = 300)
print(hist_plot)
dev.off()
```

```{r table}
table_data <- data %>% 
  select(ks_3:oh_9) %>% 
  pivot_longer(ks_3:oh_9) %>% 
  drop_na() %>% 
  mutate(value = str_sub(value, 1, 1)) %>% 
  count(name, value) %>% 
  group_by(name) %>% 
  mutate(total = sum(n)) %>% 
  ungroup() %>% 
  mutate(pct = n / total) %>% 
  select(name, value, pct) %>% 
  pivot_wider(names_from = value, values_from = pct) %>% 
  mutate(D = ifelse(is.na(D), 0, D),
         R = ifelse(is.na(R), 0, R)) %>% 
  mutate(name = toupper(name),
         name = str_replace_all(name, "_", "-")) %>% 
  arrange(name) %>% 
  select(R, name, D)

make_color_pal <- function(colors, bias = 1) {
  get_color <- colorRamp(colors, bias = bias)
  function(x) rgb(get_color(x), maxColorValue = 255)
}

rep_pct_color <- make_color_pal(c("#FFFFFF", "#F8766D"), bias = 2)
dem_pct_color <- make_color_pal(c("#FFFFFF", "#619CFF"), bias = 2)

format_pct <- function(value) {
  if (value < 0.01) " <1%"
  else if (value > 0.99) ">99%"
  else formatC(paste0(round(value * 100), "%"), width = 4)
}

pct_column_dem <- function(maxWidth = 60, class = NULL, ...) {
  colDef(
    cell = format_pct,
    maxWidth = maxWidth,
    class = paste("cell number", class),
    style = function(value) {
      # Lighter color for <1%
      if (value < 0.01) {
        list(color = "#aaa")
      } else {
        list(color = "#111", background = dem_pct_color(value))
      }
    },
    ...
  )
}

pct_column_rep <- function(maxWidth = 60, class = NULL, ...) {
  colDef(
    cell = format_pct,
    maxWidth = maxWidth,
    class = paste("cell number", class),
    style = function(value) {
      # Lighter color for <1%
      if (value < 0.01) {
        list(color = "#aaa")
      } else {
        list(color = "#111", background = rep_pct_color(value))
      }
    },
    ...
  )
}

tbl_r <- reactable(
  table_data %>% filter(R > 0.5),
  pagination = FALSE,
  defaultSorted = "name",
  defaultSortOrder = "asc",
  defaultColDef = colDef(
    align = "center",
    headerVAlign = "bottom",
    class = "cell",
    headerClass = "header"
  ),
  columns = list(
    R = pct_column_rep(name = "Rep"),
    name = colDef(width = 100, align = "center"),
    D = pct_column_dem(name = "Dem")
  ),
  showSortIcon = TRUE,
  borderless = TRUE,
  class = "table"
)

tbl_r

tbl_d <- reactable(
  table_data %>% filter(D > 0.5),
  pagination = FALSE,
  defaultSorted = "name",
  defaultSortOrder = "asc",
  defaultColDef = colDef(
    align = "center",
    headerVAlign = "bottom",
    class = "cell",
    headerClass = "header"
  ),
  columns = list(
    R = pct_column_rep(name = "Rep"),
    name = colDef(width = 100, align = "center"),
    D = pct_column_dem(name = "Dem")
  ),
  showSortIcon = TRUE,
  borderless = TRUE,
  class = "table"
)

tbl_d
```

